checks:
    javascript:
        no_var: true
        no_param_assign: true
        no_loop_var_assign: true
        no_implicit_undefined_return: true
        no_else_return: true
        no_alert: true
        eqeqeq: true

build:
    image: default-jammy
    nodes:
        analysis:
            tests:
                override:
                    - command: js-scrutinizer-run
                      idle_timeout: 1200        # 10 minutes
        tests: true
    dependencies:
        override:
            - npm install -g 'yarn'
            - command: yarn install --force
              idle_timeout: 600        # 10 minutes
