version: 2.1
orbs:
  node: circleci/node@4.4.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.21.0'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: # run tests
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: yarn test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
