# This is a basic workflow to help you get started with Actions

name: "Build deploy preview"

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      # issues: write
      pull-requests: write
      # contents: write

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: .nvmrc
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_GATSBY_API_DOMAIN: ${{ secrets.GATSBY_API_DOMAIN }}
          envkey_GATSBY_GTM_ID: ${{ secrets.GATSBY_GTM_ID }}
          envkey_KCVV_PSD_API: ${{ secrets.KCVV_PSD_API }}
          envkey_TYPEKIT_ID: ${{ secrets.TYPEKIT_ID }}

      - uses: chrnorm/deployment-action@releases/v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: "${{ github.head_ref }}"
          ref: ${{ github.event.pull_request.head.sha }}
          initial-status: pending
          transient-environment: true
          description: "Create new PR-deployment to netlify."

      - name: "Build the website"
        run: |
          yarn install --production
          yarn run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true

      - name: "Deploy to netlify server"
        uses: South-Paw/action-netlify-cli@v2
        id: deploy_preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public
      # - name: "Deploy to netlify server"
      #   uses: careflow/netlify-actions/cli@master
      #   id: deploy_preview
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     args: deploy --dir=public
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      # - name: "Deploy to netlify server"
      #   id: deploy_preview
      #   run: npx netlify deploy --dir=public
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Find the comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Netlify Preview Deployment Information

      - name: Create or update comment with preview URL.
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 This pull request is being automatically deployed to Netlify.

            ✅ Preview: ${{ steps.deploy_preview.outputs.NETLIFY_URL }}
            🔍 Inspect: ${{ steps.deploy_preview.outputs.NETLIFY_LOGS_URL }}
            📝 Output: ${{  steps.deploy_preview.outputs.NETLIFY_OUTPUT}}
          edit-mode: replace

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v2
        with:
          token: "${{ github.token }}"
          target_url: ${{ steps.deploy_preview.outputs.NETLIFY_URL }}
          environment-url: ${{ steps.deploy_preview.outputs.NETLIFY_URL }}
          log-url: ${{ steps.deploy_preview.outputs.NETLIFY_LOGS_URL }}
          state: "success"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deploy_preview.outputs.NETLIFY_URL }}
          log-url: ${{ steps.deploy_preview.outputs.NETLIFY_LOGS_URL }}
          state: "failure"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      # - name: "Deploy to netlify"
      #   uses: nwtgck/actions-netlify@v1.2.3
      #   with:
      #     publish-dir: './public'
      #     production-branch: 'master'
      #     deploy-message: '${{ github.event.head_commit.message }}'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     netlify-config-path: ./netlify.toml
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     GATSBY_GTM_ID: ${{ secrets.GATSBY_GTM_ID }}
      #     KCVV_PSD_API: ${{ secrets.KCVV_PSD_API }}
      #     GATSBY_API_DOMAIN: ${{ secrets.GATSBY_API_DOMAIN }}
