# This is a basic workflow to help you get started with Actions

name: "Build deploy preview"

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v3

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v3.0.0
        with:
          node-version-file: .nvmrc
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GATSBY_API_DOMAIN: ${{ secrets.GATSBY_API_DOMAIN }}
          envkey_GATSBY_GTM_ID: ${{ secrets.GATSBY_GTM_ID }}
          envkey_KCVV_PSD_API: ${{ secrets.KCVV_PSD_API }}

      - name: "Build the website"
        run: |
          yarn install --production
          yarn run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true

      - name: "Deploy to netlify server"
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      # - name: "Deploy to netlify"
      #   uses: nwtgck/actions-netlify@v1.2.3
      #   with:
      #     publish-dir: './public'
      #     production-branch: 'master'
      #     deploy-message: '${{ github.event.head_commit.message }}'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     netlify-config-path: ./netlify.toml
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     GATSBY_GTM_ID: ${{ secrets.GATSBY_GTM_ID }}
      #     KCVV_PSD_API: ${{ secrets.KCVV_PSD_API }}
      #     GATSBY_API_DOMAIN: ${{ secrets.GATSBY_API_DOMAIN }}
